project:
  output-dir: build
  render:
    - slides.qmd

bibliography: biblio.bib
format:
  presentation-revealjs:
    mulitplex: false
    show-notes: false
    slide-number: true
    show-slide-number: all
    controls: true
    width: 1600
    height: 900
    theme: [default, custom.scss]

filters:
  - tikz
tikz:
  cache: false

execute: 
  echo: false